//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cologne
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CologneDBEntities1 : DbContext
    {
        public CologneDBEntities1()
            : base("name=CologneDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblSabteFaktoreJadid> tblSabteFaktoreJadid { get; set; }
        public virtual DbSet<tblSabteSefaresh> tblSabteSefaresh { get; set; }
        public virtual DbSet<tblVorodeMahsol> tblVorodeMahsol { get; set; }
    
        public virtual int DeleteTblSabteFaktoreJadid(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTblSabteFaktoreJadid", iDParameter);
        }
    
        public virtual int DeleteTblSabteSefaresh(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTblSabteSefaresh", idParameter);
        }
    
        public virtual int DeletetblVorodeMahsol(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletetblVorodeMahsol", iDParameter);
        }
    
        public virtual int InsertTblSabteFaktoreJadid(Nullable<System.DateTime> tarikhKharid, Nullable<int> shomareFaktor, string raveshKharid, Nullable<System.DateTime> tarikhTasviye, Nullable<long> mablagheKoleFaktor)
        {
            var tarikhKharidParameter = tarikhKharid.HasValue ?
                new ObjectParameter("TarikhKharid", tarikhKharid) :
                new ObjectParameter("TarikhKharid", typeof(System.DateTime));
    
            var shomareFaktorParameter = shomareFaktor.HasValue ?
                new ObjectParameter("ShomareFaktor", shomareFaktor) :
                new ObjectParameter("ShomareFaktor", typeof(int));
    
            var raveshKharidParameter = raveshKharid != null ?
                new ObjectParameter("RaveshKharid", raveshKharid) :
                new ObjectParameter("RaveshKharid", typeof(string));
    
            var tarikhTasviyeParameter = tarikhTasviye.HasValue ?
                new ObjectParameter("TarikhTasviye", tarikhTasviye) :
                new ObjectParameter("TarikhTasviye", typeof(System.DateTime));
    
            var mablagheKoleFaktorParameter = mablagheKoleFaktor.HasValue ?
                new ObjectParameter("MablagheKoleFaktor", mablagheKoleFaktor) :
                new ObjectParameter("MablagheKoleFaktor", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTblSabteFaktoreJadid", tarikhKharidParameter, shomareFaktorParameter, raveshKharidParameter, tarikhTasviyeParameter, mablagheKoleFaktorParameter);
        }
    
        public virtual int InsertTblSabteSefaresh(string nameMahsol2, string hajm, Nullable<long> gheymateForosh, Nullable<System.DateTime> tarikhSabteSefaresh, string nameKharidar, Nullable<long> tel, string addressErsali)
        {
            var nameMahsol2Parameter = nameMahsol2 != null ?
                new ObjectParameter("NameMahsol2", nameMahsol2) :
                new ObjectParameter("NameMahsol2", typeof(string));
    
            var hajmParameter = hajm != null ?
                new ObjectParameter("Hajm", hajm) :
                new ObjectParameter("Hajm", typeof(string));
    
            var gheymateForoshParameter = gheymateForosh.HasValue ?
                new ObjectParameter("GheymateForosh", gheymateForosh) :
                new ObjectParameter("GheymateForosh", typeof(long));
    
            var tarikhSabteSefareshParameter = tarikhSabteSefaresh.HasValue ?
                new ObjectParameter("TarikhSabteSefaresh", tarikhSabteSefaresh) :
                new ObjectParameter("TarikhSabteSefaresh", typeof(System.DateTime));
    
            var nameKharidarParameter = nameKharidar != null ?
                new ObjectParameter("NameKharidar", nameKharidar) :
                new ObjectParameter("NameKharidar", typeof(string));
    
            var telParameter = tel.HasValue ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(long));
    
            var addressErsaliParameter = addressErsali != null ?
                new ObjectParameter("AddressErsali", addressErsali) :
                new ObjectParameter("AddressErsali", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTblSabteSefaresh", nameMahsol2Parameter, hajmParameter, gheymateForoshParameter, tarikhSabteSefareshParameter, nameKharidarParameter, telParameter, addressErsaliParameter);
        }
    
        public virtual int InsertTblVorodeMahsol(string nameMahsol, Nullable<int> tedad, string hajm, Nullable<System.DateTime> tarikhVorod, Nullable<int> gheymateKharid)
        {
            var nameMahsolParameter = nameMahsol != null ?
                new ObjectParameter("NameMahsol", nameMahsol) :
                new ObjectParameter("NameMahsol", typeof(string));
    
            var tedadParameter = tedad.HasValue ?
                new ObjectParameter("Tedad", tedad) :
                new ObjectParameter("Tedad", typeof(int));
    
            var hajmParameter = hajm != null ?
                new ObjectParameter("Hajm", hajm) :
                new ObjectParameter("Hajm", typeof(string));
    
            var tarikhVorodParameter = tarikhVorod.HasValue ?
                new ObjectParameter("TarikhVorod", tarikhVorod) :
                new ObjectParameter("TarikhVorod", typeof(System.DateTime));
    
            var gheymateKharidParameter = gheymateKharid.HasValue ?
                new ObjectParameter("GheymateKharid", gheymateKharid) :
                new ObjectParameter("GheymateKharid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTblVorodeMahsol", nameMahsolParameter, tedadParameter, hajmParameter, tarikhVorodParameter, gheymateKharidParameter);
        }
    
        public virtual int ResetIdTblSabteFaktoreJadid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResetIdTblSabteFaktoreJadid");
        }
    
        public virtual int ResetIdTblSabteSefaresh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResetIdTblSabteSefaresh");
        }
    
        public virtual int ResetIdTblVorodeMahsol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResetIdTblVorodeMahsol");
        }
    
        public virtual int UpdateTblSabteFaktoreJadid(Nullable<int> iD, Nullable<System.DateTime> tarikhKharid, Nullable<int> shomareFaktor, string raveshKharid, Nullable<System.DateTime> tarikhTasviye, Nullable<long> mablagheKoleFaktor)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tarikhKharidParameter = tarikhKharid.HasValue ?
                new ObjectParameter("TarikhKharid", tarikhKharid) :
                new ObjectParameter("TarikhKharid", typeof(System.DateTime));
    
            var shomareFaktorParameter = shomareFaktor.HasValue ?
                new ObjectParameter("ShomareFaktor", shomareFaktor) :
                new ObjectParameter("ShomareFaktor", typeof(int));
    
            var raveshKharidParameter = raveshKharid != null ?
                new ObjectParameter("RaveshKharid", raveshKharid) :
                new ObjectParameter("RaveshKharid", typeof(string));
    
            var tarikhTasviyeParameter = tarikhTasviye.HasValue ?
                new ObjectParameter("TarikhTasviye", tarikhTasviye) :
                new ObjectParameter("TarikhTasviye", typeof(System.DateTime));
    
            var mablagheKoleFaktorParameter = mablagheKoleFaktor.HasValue ?
                new ObjectParameter("MablagheKoleFaktor", mablagheKoleFaktor) :
                new ObjectParameter("MablagheKoleFaktor", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTblSabteFaktoreJadid", iDParameter, tarikhKharidParameter, shomareFaktorParameter, raveshKharidParameter, tarikhTasviyeParameter, mablagheKoleFaktorParameter);
        }
    
        public virtual int UpdateTblSabteSefaresh(Nullable<int> id, string nameMahsol2, string hajm, Nullable<long> gheymateForosh, Nullable<System.DateTime> tarikhSabteSefaresh, string nameKharidar, Nullable<long> tel, string addressErsali)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameMahsol2Parameter = nameMahsol2 != null ?
                new ObjectParameter("NameMahsol2", nameMahsol2) :
                new ObjectParameter("NameMahsol2", typeof(string));
    
            var hajmParameter = hajm != null ?
                new ObjectParameter("Hajm", hajm) :
                new ObjectParameter("Hajm", typeof(string));
    
            var gheymateForoshParameter = gheymateForosh.HasValue ?
                new ObjectParameter("GheymateForosh", gheymateForosh) :
                new ObjectParameter("GheymateForosh", typeof(long));
    
            var tarikhSabteSefareshParameter = tarikhSabteSefaresh.HasValue ?
                new ObjectParameter("TarikhSabteSefaresh", tarikhSabteSefaresh) :
                new ObjectParameter("TarikhSabteSefaresh", typeof(System.DateTime));
    
            var nameKharidarParameter = nameKharidar != null ?
                new ObjectParameter("NameKharidar", nameKharidar) :
                new ObjectParameter("NameKharidar", typeof(string));
    
            var telParameter = tel.HasValue ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(long));
    
            var addressErsaliParameter = addressErsali != null ?
                new ObjectParameter("AddressErsali", addressErsali) :
                new ObjectParameter("AddressErsali", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTblSabteSefaresh", idParameter, nameMahsol2Parameter, hajmParameter, gheymateForoshParameter, tarikhSabteSefareshParameter, nameKharidarParameter, telParameter, addressErsaliParameter);
        }
    
        public virtual int UpdateTblVorodeMahsol(Nullable<int> id, string nameMahsol, Nullable<int> tedad, string hajm, Nullable<System.DateTime> tarikhVorod, Nullable<decimal> gheymateKharid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameMahsolParameter = nameMahsol != null ?
                new ObjectParameter("NameMahsol", nameMahsol) :
                new ObjectParameter("NameMahsol", typeof(string));
    
            var tedadParameter = tedad.HasValue ?
                new ObjectParameter("Tedad", tedad) :
                new ObjectParameter("Tedad", typeof(int));
    
            var hajmParameter = hajm != null ?
                new ObjectParameter("Hajm", hajm) :
                new ObjectParameter("Hajm", typeof(string));
    
            var tarikhVorodParameter = tarikhVorod.HasValue ?
                new ObjectParameter("TarikhVorod", tarikhVorod) :
                new ObjectParameter("TarikhVorod", typeof(System.DateTime));
    
            var gheymateKharidParameter = gheymateKharid.HasValue ?
                new ObjectParameter("GheymateKharid", gheymateKharid) :
                new ObjectParameter("GheymateKharid", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTblVorodeMahsol", idParameter, nameMahsolParameter, tedadParameter, hajmParameter, tarikhVorodParameter, gheymateKharidParameter);
        }
    }
}
