//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cologne
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSabteSefaresh
    {
        public int ID { get; set; }
        public string NameMahsol2 { get; set; }
        public string Hajm { get; set; }
        public long GheymateForosh { get; set; }
        public System.DateTime TarikhSabteSefaresh { get; set; }
        public string NameKharidar { get; set; }
        public long Tel { get; set; }
        public string AddressErsali { get; set; }
    }
}
