//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cologne
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSabteFaktoreJadid
    {
        public int ID { get; set; }
        public System.DateTime TarikhKharid { get; set; }
        public int ShomareFaktor { get; set; }
        public string RaveshKharid { get; set; }
        public System.DateTime TarikhTasviye { get; set; }
        public long MablagheKoleFaktor { get; set; }
    }
}
