//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cologne
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVorodeMahsol
    {
        public int ID { get; set; }
        public string NameMahsol { get; set; }
        public int Tedad { get; set; }
        public string Hajm { get; set; }
        public System.DateTime TarikhVorod { get; set; }
        public int GheymateKharid { get; set; }
    }
}
